### ISSUE TITLE
Remove Network Permission

### ISSUE THREAD

**Issue by OwenD30** [akaMrNagar/Mindful#111]
**Have you checked it on [Project Progress](https://github.com/users/akaMrNagar/projects/1) ?**
Yes

**Is your feature request related to a problem? Please describe.**
The problem is this is a FOSS app which claims to not collect any user data, but declares network permission.

**Describe the solution you'd like**
To gain more trust with users, the app should remove the network permission so the app does not request network access. This way there is no way the app could send user data.

**Additional context**
None

**Comment by OwenD30** [comment]
I'd like to add that this app is INCREDIBLE, and I'm not accusing the developer of collecting data. I just noticed this since I use GrapheneOS and the app requests network permission. Thanks for your amazing work!

**Comment by akaMrNagar** [comment]
As you know Mindful can block another apps internet with the help of local VPN. Android does not allow apps to create and protect VPN Tunnel without the internet permission. Android throws cannot protect tunnel exception without the internet permission. So i had to declare it otherwise the feature could not work. 

To make sure that i do not collect any type of data you can check out the NETWORK usage of Mindful either in the app itself or in the device settings (If you are privacy freak like me).

I think i should clarify it in the README too  (will do it asap)

**Comment by OwenD30** [comment]
That makes perfect sense. Thanks for clarifying!
