### ISSUE TITLE
Showing Usage Statistics, Takes Time

### ISSUE THREAD

**Issue by AliNouhpisheh** [akaMrNagar/Mindful#140]
It takes (14 seconds) for me to show usage statistics every time opening the app

If it was for the first installation, preparing the app, or at least one a day, it was not noticable
but when it's about every time opening the app, it's noticable

🖼️Screenshot:
![Screenshot_2024-12-12_130207_com.mindful.android.jpg](https://github.com/user-attachments/assets/885657f4-31c3-41a6-bac0-5f1f3c118f70)

**Comment by akaMrNagar** [comment]
That's odd, can you share your device specifications like ?

**Comment by AliNouhpisheh** [comment]
Device: Redmi Note 8 Pro
CPU: MediaTek Helio G90T

With other (Screet Time apps) like 'StayFree' or 'Google's Digital Wellbeing' it takes much less time, about just (1 second)

**Comment by AliNouhpisheh** [comment]
Device: Redmi Note 8 Pro
CPU: MediaTek Helio G90T

With other (Screet Time apps) like 'StayFree' or 'Google's Digital Wellbeing' it takes much less time, about just (1 second)

**Comment by akaMrNagar** [comment]
As expected Mindful will always take more time then these apps, the particular reason is that it also fetches and calculates the data  usage for the current week too. But 14 seconds is unacceptable for my device running on Snapdragon 695  (6/128 gb) it barely takes 2,3 seconds. 

I will take a look at it though.

**Comment by akaMrNagar** [comment]
For now i have modified the code to load data faster but the main problem arises due to the fact that it loads the usage for whole week.

In future i am planning to cache the usage in database which will eventually make it faster as the app have to only request the usage for current day and the rest can be fetched from database. This will also help to store usage for longer period.

I am closing this issue for now as there is already an enhancement issue available at #115

**Comment by AliNouhpisheh** [comment]
Caching is a very good idea
Thank you ❤️❤️❤️
