### ISSUE TITLE
GrayScale Mode

### ISSUE THREAD

**Issue by Bhardwaj10Ankit** [akaMrNagar/Mindful#62]
Thanks for the great app...
Just want to request to include an option to choose for grayscale mode like the [DetoxDroid](https://github.com/flxapps/DetoxDroid) app.

**Comment by akaMrNagar** [comment]
I have initially thought to include this feature but to convert the display grayscale the app needs android.permission.WRITE_SECURE_SETTINGS permission which cannot be granted to non-system apps only the preinstalled apps have this permission.

Assuming the normal user does not have any knowledge of ADB. I cannot put the feature in app and tell the user to follow COMMANDS due to privacy concerns and use's trust (Although i prioritize user's privacy at most). 

So the feature will not make it to the app but i am not closing this issue right now, if you have any suggestions about how we could implement this without putting user accountable or without depending on user.

**Comment by Bhardwaj10Ankit** [comment]
Completely understandable, but i think having this as an additional option will not hurt anyone, yet it'll benifit the few who wish to take the risk and utilising the option....
I wish you add an extra feature group, which can include few specific features which may require some user effort to setup or the risks for those who agree to take it..... making the app more featured and not really restricting its and your capablities towards poviding a **MINDFUL** app.
btw really appreciate your efforts towards the devlopment of the app, Stay Blessed

**Comment by Bhardwaj10Ankit** [comment]
@akaMrNagar 👆🏼

**Comment by akaMrNagar** [comment]
Track project progress at https://github.com/users/akaMrNagar/projects/1
