### ISSUE TITLE
No action after enabling blocking of short-form content 

### ISSUE THREAD

**Issue by skip-jack** [akaMrNagar/Mindful#71]
**Describe the bug**
 After enabling the 'Block reels', 'Block shorts' does not produce the required action.
**To Reproduce**

1. Go to 'Wellbeing'
2. Toggle on 'Block shorts, Block reels'
3. Go to YouTube, Instagram app
4. See shorts still playing(the error).

**Expected behavior**
After selecting those radio buttons the appropriate response of the application should be:
- Blocking of short-form content on both YouTube and Instagram.

**Comment by akaMrNagar** [comment]
Blocking the shorts does not mean that it will be blocked instantly. The shorts will be blocked as soon as the short content timer ran out.

Does your timer says 0m left from time ?

**Comment by akaMrNagar** [comment]
I believe you have ignored the timer set for short content. 

![21 50 23_8ace8ff2](https://github.com/user-attachments/assets/e057e90b-8caf-4012-a13a-1686ba66203d)

**Comment by skip-jack** [comment]
Ohh my god, sorry for the oversight, yea..the feature's working perfectly,
my bad man.

Also, wanted to confirm if the timer is set to say, 45 mins...so just
opening the app, not watching the shorts also count for that time?

**Comment by akaMrNagar** [comment]
The time user spends on short content on any platform may not be accurate 100% 

Let me explain there are two ways either you put timer on the app from the app's dashboard screen or from statistics tab. This timer will be calculated based on the apps screen time regardless of the fact what you are doing.


Another timer is short content timer in well-being tab it only calculates time if you are watching shorts in the specific shorts section. The time calculation has a interval of 1 minute which is there only to improve performance and less battery drainage.

So let's say you are watching shorts then you switched to some video or other section then you come back to shorts section within a minute then the elapsed time may be included sometimes based to calculate cycle. 

That's why you may sometimes see that time is included even you are not watching shorts. I can reduce thua interval but it has more cons than pros

**Comment by akaMrNagar** [comment]
One more thing the short content time is the total time spent watching the shorts, reels of blocked platforms on their specific apps or in browsers too
